### ISSUE TITLE
Running head fails

### ISSUE THREAD

**Issue by martijnhoekstra** [dwijnand/scala-runners#18] opened 2020-05-20 17:36 UTC
```
martijn@LAPTOP-7MK8D0M5:~/scala-runners$ ./scala -2.13.head
./scala: line 34: hub: command not found
./scala: line 41: hub: command not found
./scala: line 42: jq: command not found
Resolution error: Error downloading org.scala-lang:scala-compiler:-bin-
  not found: /home/martijn/.ivy2/local/org.scala-lang/scala-compiler/-bin-/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/-bin-/scala-compiler--bin-.pom
  not found: https://scala-ci.typesafe.com/artifactory/scala-integration/org/scala-lang/scala-compiler/-bin-/scala-compiler--bin-.pom
```

Should I have done anything more than clone the repo?

**Comment by SethTisue** [comment] 2020-05-20 17:44
`brew install hub`, `brew install jq`? (or `apt-get` if you're on Linux)

but also, @dwijnand I guess https://github.com/dwijnand/homebrew-formulas/blob/master/scala-runners.rb should declare those dependencies?

**Comment by dwijnand** [comment] 2020-05-21 07:09
Duplicate of #1

**Closed as completed by dwijnand** 2020-05-21 07:09 UTC

**Comment by martijnhoekstra** [comment] 2020-05-21 09:21
That's what I tried first, but that fails for me with

```
./scala -2.13.head
git: 'api' is not a git command. See 'git --help'.
````

**Comment by dwijnand** [comment] 2020-05-21 10:25
That's very weird.  `hub api` is https://hub.github.com/hub-api.1.html, so I don't understand.  (I think the reason it says "is not a git command" is because it used to be suggested to `alias git=hub` (it's now suggested not to) and the error messages use the old idea.)

Not sure how to help... maybe `set -X` and run that again and see more info?  Or throw `set -x` inside the script.

**Comment by martijnhoekstra** [comment] 2020-05-21 11:17
maybe `apt install hub` installed something else. I'll investigate.

**Comment by martijnhoekstra** [comment] 2020-05-22 18:32
It seems hub installed what it should have installed, but still,

```
martijnhoekstra@LAPTOP-7MK8D0M5:~$ hub version
git version 2.25.1
hub version 2.7.0
martijnhoekstra@LAPTOP-7MK8D0M5:~$ hub api
git: 'api' is not a git command. See 'git --help'.

The most similar commands are
        add
        apply
        gui
```

**Comment by dwijnand** [comment] 2020-05-22 20:41
18 months old: https://github.com/github/hub/releases/tag/v2.7.0 :-/
