### ISSUE TITLE
`scala -213` (for example) picks up locally published Scalas

### ISSUE THREAD

**Issue by SethTisue** [dwijnand/scala-runners#22] opened 2020-06-24 20:46 UTC
normally, as desired:

```
% scala -213
Welcome to Scala 2.13.2 (OpenJDK 64-Bit Server VM, Java 1.8.0_252).
```

but after `hub checkout scala/scala; cd scala; sbt setupPublishCore publishLocal`, then:

```
% scala -213
Welcome to Scala 2.13.3-20200624-161150-d23424c (OpenJDK 64-Bit Server VM, Java 1.8.0_252).
```

😂😱

**Comment by dwijnand** [comment] 2020-06-26 15:11
Duplicate of #10

**Closed as completed by dwijnand** 2020-06-26 15:11 UTC
